name: C/C++ CI

on: [push]

jobs:
  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: vcpkg init
      run: git clone https://github.com/microsoft/vcpkg && cd vcpkg && ./vcpkg/bootstrap-vcpkg.sh && cd ..

    - name: Build project
      env:
        CC: gcc-10
        CXX: g++-10
      run: |
        cmake -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake .
        cmake --build .

    - name: Run tests
      run: ctest

  build_windows:
    name: Build Windows
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: |
        cmake .
        cmake --build .

    - name: Run tests
      run: ctest
